describe('Shipping Details',function(){
    it('Login valid user',function()
    {
         cy.visit("https://reference-user-web.web.app/")
         cy.contains("Login | Signup").click()
         cy.contains("Sign up").click()
         cy.contains("First Name").type("Gunjan")
         cy.contains("Last Name").type("Thakur")
         cy.get("input[type='email']").type("gunjan.3190@gmail.com")
         cy.get("input[class='w-full text-lg py-1  bg-background_grey  border-gray-300 focus:outline-none focus:border-primary border-b w-full']").type("8905825794")
    cy.get("input[type='password']").type("Thakur2023@")
    cy.contains("Register").click()
   cy.contains("Log In").click()
   cy.contains("Login with email").click()
   cy.get("input[type='email']").type("thakurgunjan531@gmail.com")
    cy.get("input[type='password']").type("Thakur2023@")
cy.contains("Log in").click()
cy.get("input[name ='pickupLocation']").type("560076")
cy.get("input[name='deliveryLocation']").type("110075")
cy.contains("document").click()
cy.get("input[name ='weight']").type("250")
cy.contains("Find Providers").click()
cy.contains("Track Shipment").click()
cy.get("input[name='awbOrderId']").type("234014256")
cy.contains("Submit").click()

})
})